################################################
#	  * @author [cb]                           #
#	  * @email [cbqin0323@gmail.com]           #
#	  * @create date 2018-05-07 02:06:17       #
#	  * @modify date 2018-05-07 02:06:17       #
#	  * @desc [YAML setting for app config]    #
################################################

default: &DEFAULT
    word2vec: /opt/word2vec/benebot_vector/word2vec.bin
    vocab_dir: ../data/vocab/
    model_dir: ../data/models/
    result_dir: ../data/results/
    summary_dir: ../data/summary/
    log_path: ~
    dataset_name: ~
dureader_debug: &DUREADER_DEBUG
    <<: *DEFAULT
    train_files: 
        - ../data/demo/dureader/trainset/search.train.json
    dev_files:
        - ../data/demo/dureader/devset/search.dev.json
    test_files:
        - ../data/demo/dureader/testset/search.test.json
    dataset_name: dureader_debug
cmrc2018_debug: &CMRC2018_DEBUG
    <<: *DEFAULT
    train_files:
        - ../data/demo/cmrc2018/trainset/train.json
    dev_files:
        - ../data/demo/cmrc2018/devset/dev.json
    test_files:
        - ../data/demo/cmrc2018/testset/test.json
    dataset_name: cmrc2018_debug
dureader: &DUREADER
    <<: *DUREADER_DEBUG
    train_files:
        - ../data/preprocessed/dureader/trainset/search.train.json
        - ../data/preprocessed/dureader/trainset/zhidao.train.json
    dev_files:
        - ../data/preprocessed/dureader/devset/search.dev.json
        - ../data/preprocessed/dureader/devset/zhidao.dev.json
    test_files:
        - ../data/preprocessed/dureader/testset/search.test.json
        - ../data/preprocessed/dureader/testset/zhidao.test.json
    dataset_name: dureader
cmrc2018: &CMRC2018
    <<: *CMRC2018_DEBUG
    train_files:
        - ../data/preprocessed/cmrc2018/trainset/train.json
    dev_files:
        - ../data/preprocessed/cmrc2018/devset/dev.json
    test_files:
        - ../data/preprocessed/cmrc2018/testset/test.json
    dataset_name: cmrc2018 