##############################################
#	* @author [cb]                           #
#	* @email [cbqin0323@gmail.com]           #
#	* @create date 2018-05-07 02:06:17       #
#	* @modify date 2018-05-07 02:06:17       #
#	* @desc [YAML setting for model params]  #
##############################################

default: &DEFAULT
    cell: lstm
    optim: adagrad
    learning_rate: 0.001
    weight_decay: 0
    dropout_keep_prob: 1
    batch_size: 2
    epochs: 20
    word_embed_dim: 300
    char_embed_dim: 300
    hidden_size: 150
    max_p_num: 1
    max_p_len: 500
    max_q_len: 60
    max_a_len: 200
    max_char_len: 4
    num_gpu: 1
qanet: &QANET
    <<: *DEFAULT
    l2_norm: 3e-7
    dropout: 0.1
    decay: 0.9999
    num_head: 1
    grad_clip: 5.0